name: Run Tests
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.0-beta.4'
      
      - name: Setup Python Virtual Environment
        run: python3 -m venv python3-virtualenv

      - name: Install Dependencies
        run: python3-virtualenv/bin/pip install -r requirements.txt

      - name: Make run_test.sh executable
        run: chmod +x ./run-test.sh

      - name: Run Tests
        run: ./run-test.sh
